trigger:
  - main

pool:
  vmImage: "ubuntu-24.04"

variables:
  solution: "web/JobCompaniesWeb.sln"
  serviceConnection: "ado-spn-unstacked-jobcompanies-dev-ukwest"
  tfstateResourceGroupName: "rg-unstacked-jobcompanies-dev-ukwest"
  tfstateStorageAccountName: "stjobcompaniesdevukwest"

stages:
  - stage: Build
    jobs:
      - job: BuildJob
        steps:

          - task: UseDotNet@2
            displayName: 'Use .NET 8'
            inputs:
              version: '8.0.x'

          - pwsh: dotnet restore $(solution)
            displayName: 'Restore'

          - pwsh: dotnet build $(solution) --configuration Release --no-restore
            displayName: 'Build'

          - pwsh: dotnet publish $(solution) --configuration Release --no-build --output $(Build.ArtifactStagingDirectory)/publish
            displayName: 'Publish'

          - task: ArchiveFiles@2
            displayName: 'Compress Web App'
            inputs:
              rootFolderOrFile: '$(Build.ArtifactStagingDirectory)/publish'
              includeRootFolder: false
              archiveType: 'zip'
              archiveFile: '$(Build.ArtifactStagingDirectory)/web.zip'
              replaceExistingArchive: true

          - task: PublishPipelineArtifact@1
            displayName: "Publish Artifact (web)"
            inputs:
              targetPath: "$(Build.ArtifactStagingDirectory)/web.zip"
              artifact: "drop_web"

          - task: PublishPipelineArtifact@1
            displayName: "Publish Artifact (infra)"
            inputs:
              targetPath: "$(Build.SourcesDirectory)/infra"
              artifact: "drop_infra"

  - stage: Deploy
    dependsOn: Build
    jobs:
      - deployment: DeployInfraAndWeb
        environment: "dev" 
        strategy:
          runOnce:
            deploy:
              steps:
                - download: current
                  artifact: drop_infra
                - download: current
                  artifact: drop_web

                - task: TerraformInstaller@1
                  displayName: "Install Terraform"
                  inputs:
                    terraformVersion: "1.7.0"

                - task: TerraformTaskV4@4
                  displayName: "Terraform Init"
                  inputs:
                    provider: "azurerm"
                    command: "init"
                    workingDirectory: "$(Pipeline.Workspace)/drop_infra"
                    backendServiceArm: "$(serviceConnection)"
                    backendAzureRmResourceGroupName: "$(tfstateResourceGroupName)"
                    backendAzureRmStorageAccountName: "$(tfstateStorageAccountName)"
                    backendAzureRmContainerName: "tfstate"
                    backendAzureRmKey: "terraform.tfstate"

                - task: TerraformTaskV4@4
                  displayName: "Terraform Apply"
                  inputs:
                    provider: "azurerm"
                    command: "apply"
                    workingDirectory: "$(Pipeline.Workspace)/drop_infra"
                    environmentServiceNameAzureRM: "$(serviceConnection)"
                    commandOptions: "-auto-approve"

                - task: AzureCLI@2
                  displayName: "Capture Terraform Variables"
                  inputs:
                    azureSubscription: "$(serviceConnection)"
                    scriptType: "pscore"
                    scriptLocation: "inlineScript"
                    workingDirectory: "$(Pipeline.Workspace)/drop_infra"
                    inlineScript: |
                      $appServiceName = terraform output -raw app_service_name
                      Write-Host "App Service name: $appServiceName"
                      Write-Host "##vso[task.setvariable variable=webAppName]$appServiceName"

                - task: AzureRmWebAppDeployment@4
                  displayName: "Deploy Azure App Service"
                  inputs:
                    ConnectionType: "AzureRM"
                    azureSubscription: "$(serviceConnection)"
                    appType: "webApp"
                    WebAppName: "$(webAppName)"
                    Package: "$(Pipeline.Workspace)/drop_web/**/*.zip"
